/**
 * Enumeration of supported ISO-639-1 language codes.
 * Kept in alphabetical order by enum key
 */
export enum SupportedLang {
  AF  = "af",  // Afrikaans
  AR  = "ar",  // Arabic
  AZ  = "az",  // Azerbaijani
  BE  = "be",  // Belarusian
  BG  = "bg",  // Bulgarian
  BN  = "bn",  // Bengali
  BS  = "bs",  // Bosnian
  CA  = "ca",  // Catalan
  CEB = "ceb", // Cebuano
  CO  = "co",  // Corsican
  CS  = "cs",  // Czech
  CY  = "cy",  // Welsh
  DA  = "da",  // Danish
  DE  = "de",  // German
  EL  = "el",  // Greek
  EN  = "en",  // English
  EO  = "eo",  // Esperanto
  ES  = "es",  // Spanish
  ET  = "et",  // Estonian
  EU  = "eu",  // Basque
  FA  = "fa",  // Persian
  FIL = "fil", // Filipino
  FI  = "fi",  // Finnish
  FR  = "fr",  // French
  GA  = "ga",  // Irish
  GD  = "gd",  // Gaelic
  GL  = "gl",  // Galician
  GN  = "gn",  // Guarani
  GU  = "gu",  // Gujarati
  HA  = "ha",  // Hausa
  HE  = "he",  // Hebrew
  HI  = "hi",  // Hindi
  HMN = "hmn", // Hmong
  HT  = "ht",  // Haitian Creole
  HR  = "hr",  // Croation
  HU  = "hu",  // Hungarian
  HY  = "hy",  // Armenian
  ID  = "id",  // Indonesian
  IG  = "ig",  // Igbo
  IS  = "is",  // Icelandic
  IT  = "it",  // Italian
  JA  = "ja",  // Japanese
  JV  = "jv",  // Javanese
  KA  = "ka",  // Georgian
  KK  = "kk",  // Kazakh
  KO  = "ko",  // Korean
  KM  = "km",  // Khmer
  KN  = "kn",  // Kannada
  LA  = "la",  // Latin
  LB  = "lb",  // Luxembourgish
  LO  = "lo",  // Lao
  LT  = "lt",  // Lithuanian
  LV  = "lv",  // Latvian
  MG  = "mg",  // Malagasy
  MI  = "mi",  // Māori
  MK  = "mk",  // Macedonian
  ML  = "ml",  // Malayalam
  MN  = "mn",  // Mongolian
  MR  = "mr",  // Marathi
  MS  = "ms",  // Malay
  MT  = "mt",  // Maltese
  MY  = "my",  // Burmese
  NB  = "nb",  // Norwegian Bokmål
  NE  = "ne",  // Nepali
  NL  = "nl",  // Dutch
  NN  = "nn",  // Norwegian Nynorsk
  NO  = "no",  // Norwegian
  NY  = "ny",  // Chichewa
  OC  = "oc",  // Occitan
  PA  = "pa",  // Punjabi
  PL  = "pl",  // Polish
  PT  = "pt",  // Portuguese
  RM  = "rm",  // Romansh
  RO  = "ro",  // Romanian
  RUP = "rup", // Aromanian
  RU  = "ru",  // Russian
  SA  = "sa",  // Sanskrit
  SC  = "sc",  // Sardinian
  SE  = "se",  // Northern Sami
  SI  = "si",  // Sinhala
  SK  = "sk",  // Slovak
  SL  = "sl",  // Slovenian
  SO  = "so",  // Somali
  SQ  = "sq",  // Albanian
  SR  = "sr",  // Serbian
  ST  = "st",  // Southern Sotho
  SU  = "su",  // Sudanese
  SV  = "sv",  // Swedish
  SW  = "sw",  // Swahili
  TA  = "ta",  // Tamil
  TE  = "te",  // Telugu
  TH  = "th",  // Thai
  TL  = "tl",  // Tagalog
  TG  = "tg",  // Tajik
  TK  = "tk",  // Turkmen
  TR  = "tr",  // Turkish
  UND = "und", // Undefined
  UR  = "ur",  // Urdu
  UK  = "uk",  // Ukrainian
  UZ  = "uz",  // Uzbek
  VI  = "vi",  // Vietnamese, 
  ZH  = "zh"   // Chinese
}
