FROM solr:8.11.2

USER root

# Create folder for the plugin
RUN mkdir -p /opt/solr/contrib/analysis-extras/lib

# Download the jar file necessary for the ICU plugin
RUN curl -sSL -o /opt/solr/contrib/analysis-extras/lib/solr-analysis-extras.jar \
    https://repo1.maven.org/maven2/org/apache/solr/solr-analysis-extras/8.11.2/solr-analysis-extras-8.11.2.jar

# Permissions for solr
RUN chown -R solr:solr /opt/solr/contrib

USER solr
